# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6ae8e8666e399e83d5292a15d712974d0dd0d09148be2126cdeb3bbbacea602eba76f27a48ccad78e0278413816536d767a3ec1fad7f907f11593298060dcd3

test:
  secret_key_base: a6dbf44ab749f35532ea1972fa088d3252eeea2cff7b663ff2525b5628b0339731a4639aa0230845fb6b1fae259019984cad34b6bf957624941a0d9d16afba96

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
